### ISSUE TITLE
Fails if you enter the wrong Plex Username and Password directly

### ISSUE THREAD

**Issue by KaraokeStu** [pannal/Kitana#17]
Running in Docker with the following docker-compose file:

```
version: '2'
services:
  plugins:
    container_name: plugins
    image: pannal/kitana:latest
    command: -P -PH X-Forwarded-Host
    volumes:
      - /etc/docker/kitana:/app/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID=1000
      - PUID=1000
    network_mode: host
    depends_on:
      - plex
    restart: unless-stopped
```

The docker container is running behind Traefik, which is forwarding the host "https://plugins.xxx.yyy" to the container correctly.

The server briefly looks to work, but then comes up with a gorgeous 500 error:
```
500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/cherrypy/_cprequest.py", line 628, in respond
    self._do_respond(path_info)
  File "/usr/local/lib/python3.5/site-packages/cherrypy/_cprequest.py", line 687, in _do_respond
    response.body = self.handler()
  File "/usr/local/lib/python3.5/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "kitana.py", line 458, in get_plex_token
    r.raise_for_status()
  File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://plex.tv/users/sign_in.json
```

**Comment by KaraokeStu** [comment]
I found the issue here - if you put the password in wrong, then it falls over with the 401 error - it should be a little more graceful and let the user know

**Comment by raulvasquez** [comment]
`
  kitana:
    container_name: kitana
    image: pannal/kitana:latest
    restart: always
    command: -P
    depends_on:
      - plex
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 31337:31337
    volumes:
      - ${USERDIR}/docker/kitana:/app/data
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=plex"
      - "traefik.frontend.rule=Host:kitana.${DOMAINNAME}"
      - "traefik.port=31337"
      - "traefik.docker.network=traefik_proxy"
`

I am trying to figure out why my kitana will not load. I get a connection timed out error.

The docker logs show:

`[11/Oct/2019:13:52:58] ENGINE Bus STARTING,
[11/Oct/2019:13:52:58] ENGINE Starting SassCompilerPlugin,
[11/Oct/2019:13:52:58] ENGINE Started monitor thread 'UpdateCheck'.,
[11/Oct/2019:13:52:58] ENGINE Serving on http://0.0.0.0:31337,
[11/Oct/2019:13:52:58] ENGINE Bus STARTED,
[11/Oct/2019:13:52:58]  Starting Sass Compile,
[11/Oct/2019:13:52:58]  SassCompilerPlugin: Compiling /app/static/sass to /app/static/css,
[11/Oct/2019:13:52:59] ENGINE Listening for SIGHUP.,
[11/Oct/2019:13:52:59] ENGINE Listening for SIGTERM.,
[11/Oct/2019:13:52:59] ENGINE Listening for SIGUSR1.,`

**Comment by pannal** [comment]
@raulvasquez please open a separate issue.
