### ISSUE TITLE
Get my logs

### ISSUE THREAD

**Issue by mouzzampk2014** [pannal/Kitana#22]
Hi, after 0.2.0 update when I click on Get my Logs I am getting this message 
```
192.168.1.88 - - [11/Nov/2019:10:33:45] "GET /video/subzero/advanced HTTP/1.1" 200 22432 "http://192.168.1.52:31337/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18362"
Something went wrong. Traceback (most recent call last):
  File "kitana.py", line 572, in default
    return self.render_plugin(path)
  File "kitana.py", line 175, in render_plugin
    is_current_pms = filter(lambda c: c["address"] == f.host or f.host in c["url"], self.connections)
TypeError: 'NoneType' object is not iterable
```
Thank you

**Comment by pannal** [comment]
Yes, as I wrote in the other ticket you need to re-select your server once. Afterwards it should work.

**Comment by mouzzampk2014** [comment]
> Yes, as I wrote in the other ticket you need to re-select your server once. Afterwards it should work.

Nice one. Working perfectly fine. Much appreciated. Thank you
