### ISSUE TITLE
Not working with docker-compose

### ISSUE THREAD

**Issue by zucram** [pannal/Kitana#3]
Tried adding Kitana to my docker compose file but seems to be not working correctly (probably my fault). 
**Docker Compose file:** 
 

```
# Kitana
  kitana:
    container_name: kitana
    hostname: kitana
    restart: always
    image: pannal/kitana:latest
    volumes:
      - ${USERDIR}/docker/kitana_data:/app/data
      - ${USERDIR}/docker/shared:/shared
    ports:
      - "31337:31337"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
```

**Error message when browsing to 31337**
 ```
 File "/usr/local/lib/python3.5/site-packages/zc/lockfile/__init__.py", line 79, in __init__
    fp = open(path, 'r+')
FileNotFoundError: [Errno 2] No such file or directory: '/app/data/sessions/session-37a46083e836526c036c9602f112785459e11e93.lock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/cherrypy/_cprequest.py", line 628, in respond
    self._do_respond(path_info)
  File "/usr/local/lib/python3.5/site-packages/cherrypy/_cprequest.py", line 678, in _do_respond
    self.hooks.run('before_request_body')
  File "/usr/local/lib/python3.5/site-packages/cherrypy/_cprequest.py", line 114, in run
    raise exc
  File "/usr/local/lib/python3.5/site-packages/cherrypy/_cprequest.py", line 104, in run
    hook()
  File "/usr/local/lib/python3.5/site-packages/cherrypy/_cprequest.py", line 63, in __call__
    return self.callback(**self.kwargs)
  File "/usr/local/lib/python3.5/site-packages/cherrypy/_cptools.py", line 280, in _lock_session
    cherrypy.serving.session.acquire_lock()
  File "/usr/local/lib/python3.5/site-packages/cherrypy/lib/sessions.py", line 557, in acquire_lock
    self.lock = zc.lockfile.LockFile(path)
  File "/usr/local/lib/python3.5/site-packages/zc/lockfile/__init__.py", line 85, in __init__
    fp = open(path, 'a+')
FileNotFoundError: [Errno 2] No such file or directory: '/app/data/sessions/session-37a46083e836526c036c9602f112785459e11e93.lock'
```

**Comment by pannal** [comment]
Are you on the latest version of the docker image? That shouldn't happen, as the sessions folder should be automatically created inside the container.

**Comment by zucram** [comment]
Yes i used the latest image.

**Comment by zucram** [comment]
Any update on this @pannal ???

**Comment by marine1988** [comment]
hi there mine has same problem with last image not working
