### ISSUE TITLE
Suddenly Kitana Docker stopped working

### ISSUE THREAD

**Issue by Cyb3rGh05t** [pannal/Kitana#35]
Hi,

i dont know why but since today kitana stopped working, i get this error in logs:

`[21/Mar/2020:22:52:36] ENGINE Bus STARTING

[21/Mar/2020:22:52:36] ENGINE Starting SassCompilerPlugin

[21/Mar/2020:22:52:36] ENGINE Serving on http://0.0.0.0:31337

[21/Mar/2020:22:52:36] ENGINE Bus STARTED

[21/Mar/2020:22:52:36]  Starting Sass Compile

[21/Mar/2020:22:52:36]  SassCompilerPlugin: Compiling /app/static/sass to /app/static/css

[21/Mar/2020:22:52:37] ENGINE Listening for SIGHUP.

[21/Mar/2020:22:52:37] ENGINE Listening for SIGUSR1.

[21/Mar/2020:22:52:37] ENGINE Listening for SIGTERM.

[21/Mar/2020:22:52:42] ENGINE Started monitor thread 'Session cleanup'.

Something went wrong. Traceback (most recent call last):

  File "/usr/local/lib/python3.5/site-packages/urllib3/connection.py", line 157, in _new_conn

    (self._dns_host, self.port), self.timeout, **extra_kw

  File "/usr/local/lib/python3.5/site-packages/urllib3/util/connection.py", line 84, in create_connection

    raise err

  File "/usr/local/lib/python3.5/site-packages/urllib3/util/connection.py", line 74, in create_connection

    sock.connect(sa)

ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 672, in urlopen

    chunked=chunked,

  File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 376, in _make_request

    self._validate_conn(conn)

  File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn

    conn.connect()

  File "/usr/local/lib/python3.5/site-packages/urllib3/connection.py", line 300, in connect

    conn = self._new_conn()

  File "/usr/local/lib/python3.5/site-packages/urllib3/connection.py", line 169, in _new_conn

    self, "Failed to establish a new connection: %s" % e

urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7febab82d6d8>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/lib/python3.5/site-packages/requests/adapters.py", line 449, in send

    timeout=timeout

  File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 720, in urlopen

    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]

  File "/usr/local/lib/python3.5/site-packages/urllib3/util/retry.py", line 436, in increment

    raise MaxRetryError(_pool, url, error or ResponseError(cause))

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='172-17-0-9.169fc7620e074c7681d011c86f0f315e.plex.direct', port=32400): Max retries exceeded with url: /video/subzero (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7febab82d6d8>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "kitana.py", line 632, in default

    return self.render_plugin(path)

  File "kitana.py", line 174, in render_plugin

    content = self.plex_dispatch(path)

  File "kitana.py", line 159, in plex_dispatch

    r = self._dispatch(path)

  File "kitana.py", line 154, in _dispatch

    r = self.session.get(self.server_addr + path, headers=headers, params=data, **self.req_defaults)

  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 546, in get

    return self.request('GET', url, **kwargs)

  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 533, in request

    resp = self.send(prep, **send_kwargs)

  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 646, in send

    r = adapter.send(request, **kwargs)

  File "/usr/local/lib/python3.5/site-packages/requests/adapters.py", line 516, in send

    raise ConnectionError(e, request=request)

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='172-17-0-9.169fc7620e074c7681d011c86f0f315e.plex.direct', port=32400): Max retries exceeded with url: /video/subzero (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7febab82d6d8>: Failed to establish a new connection: [Errno 111] Connection refused',))`

Is there anything i can do to fix this?

thanks in advance

**Comment by pannal** [comment]
Can you try reverting to the last release?

**Comment by Cyb3rGh05t** [comment]
How can i do this in docker?

**Comment by pannal** [comment]
Use `pannal/kitana:0.3.1-3` instead of `pannal/kitana:latest` when running the container.

**Comment by Cyb3rGh05t** [comment]
thanks that worked :)

Kitana is running again.

Thanks for your support

**Comment by k00d1** [comment]
I'm trying with 0.3.1-3 and I'm still getting errors.

[17/May/2020:08:46:23] ENGINE Bus STARTING
[17/May/2020:08:46:23] ENGINE Starting SassCompilerPlugin
[17/May/2020:08:46:23] ENGINE Serving on http://0.0.0.0:31337
[17/May/2020:08:46:23] ENGINE Bus STARTED
[17/May/2020:08:46:23] Starting Sass Compile
[17/May/2020:08:46:23] SassCompilerPlugin: Compiling /app/static/sass to /app/static/css
[17/May/2020:08:46:24] ENGINE Listening for SIGHUP.
[17/May/2020:08:46:24] ENGINE Listening for SIGUSR1.
[17/May/2020:08:46:24] ENGINE Listening for SIGTERM.
[17/May/2020:08:46:37] ENGINE Started monitor thread 'Session cleanup'.

Something went wrong. Traceback (most recent call last):
File "/usr/local/lib/python3.5/site-packages/urllib3/connection.py", line 157, in _new_conn (self._dns_host, self.port), self.timeout, **extra_kw

File "/usr/local/lib/python3.5/site-packages/urllib3/util/connection.py", line 84, in create_connection

raise err

File "/usr/local/lib/python3.5/site-packages/urllib3/util/connection.py", line 74, in create_connection

sock.connect(sa)

ConnectionRefusedError: [Errno 111] Connection refused


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 672, in urlopen

chunked=chunked,

File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 376, in _make_request

self._validate_conn(conn)

File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn

conn.connect()

File "/usr/local/lib/python3.5/site-packages/urllib3/connection.py", line 300, in connect

conn = self._new_conn()

File "/usr/local/lib/python3.5/site-packages/urllib3/connection.py", line 169, in _new_conn

self, "Failed to establish a new connection: %s" % e

urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f6c9afaae10>: Failed to establish a new connection: [Errno 111] Connection refused

File "/usr/local/lib/python3.5/site-packages/requests/adapters.py", line 449, in send

timeout=timeout

File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 720, in urlopen

method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]

File "/usr/local/lib/python3.5/site-packages/urllib3/util/retry.py", line 436, in increment

raise MaxRetryError(_pool, url, error or ResponseError(cause))

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='XX-XXX-XXX-XXX.9a116bbdf410476ebe36d790c89f94fa.plex.direct', port=32400): Max retries exceeded with url: /video/subzero (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6c9afaae10>: Failed to establish a new connection: [Errno 111] Connection refused',))

File "kitana.py", line 632, in default

return self.render_plugin(path)

File "kitana.py", line 174, in render_plugin

content = self.plex_dispatch(path)

File "kitana.py", line 159, in plex_dispatch

r = self._dispatch(path)

File "kitana.py", line 154, in _dispatch

r = self.session.get(self.server_addr + path, headers=headers, params=data, **self.req_defaults)

File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 546, in get

return self.request('GET', url, **kwargs)

File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 533, in request

resp = self.send(prep, **send_kwargs)

File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 646, in send

r = adapter.send(request, **kwargs)

File "/usr/local/lib/python3.5/site-packages/requests/adapters.py", line 516, in send

raise ConnectionError(e, request=request)

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='XX-XXX-XXX-XXX.9a116bbdf410476ebe36d790c89f94fa.plex.direct', port=32400): Max retries exceeded with url: /video/subzero (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6c9afaae10>: Failed to establish a new connection: [Errno 111] Connection refused',))

172.17.0.1 - - [17/May/2020:08:46:41] "GET / HTTP/1.1" 200 - "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:76.0) Gecko/20100101 Firefox/76.0"

**Comment by pannal** [comment]
@k00d1 please upgrade to the latest release.

**Comment by k00d1** [comment]
> @k00d1 please upgrade to the latest release.

After upgrading:

[17/May/2020:21:41:17] ENGINE Bus STARTING

[17/May/2020:21:41:17] ENGINE Starting SassCompilerPlugin

[17/May/2020:21:41:17] ENGINE Serving on http://0.0.0.0:31337

[17/May/2020:21:41:17] ENGINE Bus STARTED

[17/May/2020:21:41:17] Starting Sass Compile

[17/May/2020:21:41:17] SassCompilerPlugin: Compiling /app/static/sass to /app/static/css

[17/May/2020:21:41:18] ENGINE Listening for SIGHUP.

[17/May/2020:21:41:18] ENGINE Listening for SIGTERM.

[17/May/2020:21:41:18] ENGINE Listening for SIGUSR1.

[17/May/2020:21:41:36] ENGINE Started monitor thread 'Session cleanup'.

172.17.0.1 - - [17/May/2020:21:41:36] "GET /favicon.ico HTTP/1.1" 200 1150 "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:76.0) Gecko/20100101 Firefox/76.0"

Something went wrong. Traceback (most recent call last):

File "/usr/local/lib/python3.5/site-packages/urllib3/connection.py", line 157, in _new_conn

(self._dns_host, self.port), self.timeout, **extra_kw

File "/usr/local/lib/python3.5/site-packages/urllib3/util/connection.py", line 84, in create_connection

raise err

File "/usr/local/lib/python3.5/site-packages/urllib3/util/connection.py", line 74, in create_connection

sock.connect(sa)

ConnectionRefusedError: [Errno 111] Connection refused


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 672, in urlopen

chunked=chunked,

File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 376, in _make_request

self._validate_conn(conn)

File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn

conn.connect()

File "/usr/local/lib/python3.5/site-packages/urllib3/connection.py", line 300, in connect

conn = self._new_conn()

File "/usr/local/lib/python3.5/site-packages/urllib3/connection.py", line 169, in _new_conn

self, "Failed to establish a new connection: %s" % e

urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f77d9a8f3c8>: Failed to establish a new connection: [Errno 111] Connection refused

File "/usr/local/lib/python3.5/site-packages/requests/adapters.py", line 449, in send

timeout=timeout

File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 720, in urlopen

method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]

File "/usr/local/lib/python3.5/site-packages/urllib3/util/retry.py", line 436, in increment

raise MaxRetryError(_pool, url, error or ResponseError(cause))

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='XX-XXX-XXX-XXX.9a116bbdf410476ebe36d790c89f94fa.plex.direct', port=32400): Max retries exceeded with url: /video/subzero (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f77d9a8f3c8>: Failed to establish a new connection: [Errno 111] Connection refused',))

File "kitana.py", line 632, in default

return self.render_plugin(path)

File "kitana.py", line 174, in render_plugin

content = self.plex_dispatch(path)

File "kitana.py", line 159, in plex_dispatch

r = self._dispatch(path)

File "kitana.py", line 154, in _dispatch

r = self.session.get(self.server_addr + path, headers=headers, params=data, **self.req_defaults)

File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 543, in get

return self.request('GET', url, **kwargs)

File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 530, in request

resp = self.send(prep, **send_kwargs)

File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 643, in send

r = adapter.send(request, **kwargs)

File "/usr/local/lib/python3.5/site-packages/requests/adapters.py", line 516, in send

raise ConnectionError(e, request=request)

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='XX-XXX-XXX-XXX.9a116bbdf410476ebe36d790c89f94fa.plex.direct', port=32400): Max retries exceeded with url: /video/subzero (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f77d9a8f3c8>: Failed to establish a new connection: [Errno 111] Connection refused',))

172.17.0.1 - - [17/May/2020:21:41:40] "GET / HTTP/1.1" 200 - "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:76.0) Gecko/20100101 Firefox/76.0"

**Comment by k00d1** [comment]
Should I open a new ticket?
