### ISSUE TITLE
401 Unauthorized when opening any content

### ISSUE THREAD

**Issue by jallen2281** [pannal/Kitana#39]
Hi there,

Kitana itself works, and you can browse through all the available content, however, if you click on certain channels shows, you get this:
`Error on Plexy (see log): 500 Server Error: Internal Server Error for url: https://192-168-10-60.ab702f58bd984d18abd3648e3cb7a6af.plex.direct:32400/video/lifetime/seasons?title=24%20To%20Life&url=http://www.mylifetime.com/shows/24-to-life`

If you follow the URL in the error, you get a 401 Unauthorized error.

I've also verified that this same problem exists locally, if you append the uri to the server, although I'm not sure that even SHOULD work? (http://<ip>:<port>/video/lifetime/seasons?title=24%20To%20Life&url=http://www.mylifetime.com/shows/24-to-life)

Some of the shows that open outside of the app in their own window are working fine. i.e - The CW, or HGTV Canada shows.

Any help is appreciated.

**Comment by jhackeur** [comment]
Hi,
I got exactly the same issue - no solution find yet...

**Comment by pannal** [comment]
Is this still an issue?

**Comment by timothevs** [comment]
Hi @pannal , yes this is still an issue. I have tried all modes, Direct, Relay, and remote.

**Comment by ewascome** [comment]
Not working for me either.

**Comment by githubJond** [comment]
same here - got following answer when i put the url manually:
<Response code="2000" status="HTTPError: ">
<Traceback>Traceback (most recent call last): File "/usr/lib/plexmediaserver/Resources/Plug-ins-1b7748a7b/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 843, in handle_request result = f(**d) File "/usr/lib/plexmediaserver/Resources/Plug-ins-1b7748a7b/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/handlers/base.py", line 122, in call identifier = self._core.identifier File "/usr/lib/plexmediaserver/Resources/Plug-ins-1b7748a7b/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/messaging.py", line 86, in call_external_function packed_result = self._core.networking.http_request(url, cacheTime=0, timeout=None, immediate=True).content File "/usr/lib/plexmediaserver/Resources/Plug-ins-1b7748a7b/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 346, in http_request return HTTPRequest(self._core, url, data, h, url_cache, encoding, errors, timeout, immediate, sleep, opener, follow_redirects, method) File "/usr/lib/plexmediaserver/Resources/Plug-ins-1b7748a7b/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 118, in __init__ self.load() File "/usr/lib/plexmediaserver/Resources/Plug-ins-1b7748a7b/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 158, in load f = self._opener.open(req, timeout=self._timeout) File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/urllib2.py", line 435, in open response = meth(req, response) File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/urllib2.py", line 548, in http_response 'http', request, response, code, msg, hdrs) File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/urllib2.py", line 473, in error return self._call_chain(*args) File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/urllib2.py", line 407, in _call_chain result = func(*args) File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/urllib2.py", line 556, in http_error_default raise HTTPError(req.get_full_url(), code, msg, hdrs, fp) HTTPError: HTTP Error 404: Not Found </Traceback>
</Response>


Any solution for this - need to do a full sync with the trakt-scrobbler plug-in

**Comment by pannal** [comment]
Wait. Just because you're all seeing something vaguely _similar_ doesn't mean you have the same issues as the OP.

OP sees a 401 because he tried opening a Plex URL without supplying X-Plex-Token. That's normal. His issue is probably originally because of the full unescaped http URL in his parameter.

I can only help you individually if you supply sufficient logs and information about your environments.

**Comment by pannal** [comment]
@jallen2281 please provide logs for the original issue

**Comment by gitthangbaby** [comment]
i was looking for the solution for one year, finally found the token (somehow secretive) in Plex movie infor -> XML.

**Comment by pannal** [comment]
Well yeah, it's public information: https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/
