### ISSUE TITLE
Errno 111 connection refused

### ISSUE THREAD

**Issue by k00d1** [pannal/Kitana#40]
> @k00d1 please upgrade to the latest release.

After upgrading:

[17/May/2020:21:41:17] ENGINE Bus STARTING

[17/May/2020:21:41:17] ENGINE Starting SassCompilerPlugin

[17/May/2020:21:41:17] ENGINE Serving on http://0.0.0.0:31337

[17/May/2020:21:41:17] ENGINE Bus STARTED

[17/May/2020:21:41:17] Starting Sass Compile

[17/May/2020:21:41:17] SassCompilerPlugin: Compiling /app/static/sass to /app/static/css

[17/May/2020:21:41:18] ENGINE Listening for SIGHUP.

[17/May/2020:21:41:18] ENGINE Listening for SIGTERM.

[17/May/2020:21:41:18] ENGINE Listening for SIGUSR1.

[17/May/2020:21:41:36] ENGINE Started monitor thread 'Session cleanup'.

172.17.0.1 - - [17/May/2020:21:41:36] "GET /favicon.ico HTTP/1.1" 200 1150 "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:76.0) Gecko/20100101 Firefox/76.0"

Something went wrong. Traceback (most recent call last):

File "/usr/local/lib/python3.5/site-packages/urllib3/connection.py", line 157, in _new_conn

(self._dns_host, self.port), self.timeout, **extra_kw

File "/usr/local/lib/python3.5/site-packages/urllib3/util/connection.py", line 84, in create_connection

raise err

File "/usr/local/lib/python3.5/site-packages/urllib3/util/connection.py", line 74, in create_connection

sock.connect(sa)

ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 672, in urlopen

chunked=chunked,

File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 376, in _make_request

self._validate_conn(conn)

File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn

conn.connect()

File "/usr/local/lib/python3.5/site-packages/urllib3/connection.py", line 300, in connect

conn = self._new_conn()

File "/usr/local/lib/python3.5/site-packages/urllib3/connection.py", line 169, in _new_conn

self, "Failed to establish a new connection: %s" % e

urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f77d9a8f3c8>: Failed to establish a new connection: [Errno 111] Connection refused

File "/usr/local/lib/python3.5/site-packages/requests/adapters.py", line 449, in send

timeout=timeout

File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 720, in urlopen

method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]

File "/usr/local/lib/python3.5/site-packages/urllib3/util/retry.py", line 436, in increment

raise MaxRetryError(_pool, url, error or ResponseError(cause))

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='XX-XXX-XXX-XXX.9a116bbdf410476ebe36d790c89f94fa.plex.direct', port=32400): Max retries exceeded with url: /video/subzero (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f77d9a8f3c8>: Failed to establish a new connection: [Errno 111] Connection refused',))

File "kitana.py", line 632, in default

return self.render_plugin(path)

File "kitana.py", line 174, in render_plugin

content = self.plex_dispatch(path)

File "kitana.py", line 159, in plex_dispatch

r = self._dispatch(path)

File "kitana.py", line 154, in _dispatch

r = self.session.get(self.server_addr + path, headers=headers, params=data, **self.req_defaults)

File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 543, in get

return self.request('GET', url, **kwargs)

File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 530, in request

resp = self.send(prep, **send_kwargs)

File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 643, in send

r = adapter.send(request, **kwargs)

File "/usr/local/lib/python3.5/site-packages/requests/adapters.py", line 516, in send

raise ConnectionError(e, request=request)

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='XX-XXX-XXX-XXX.9a116bbdf410476ebe36d790c89f94fa.plex.direct', port=32400): Max retries exceeded with url: /video/subzero (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f77d9a8f3c8>: Failed to establish a new connection: [Errno 111] Connection refused',))

172.17.0.1 - - [17/May/2020:21:41:40] "GET / HTTP/1.1" 200 - "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:76.0) Gecko/20100101 Firefox/76.0"

_Originally posted by @k00d1 in https://github.com/pannal/Kitana/issues/35#issuecomment-629865393_

**Comment by k00d1** [comment]
Would love to get this fixed, anything I could try or do?

**Comment by k00d1** [comment]
@pannal still no working fix?

**Comment by pannal** [comment]
What's the version that Kitana shows?

**Comment by k00d1** [comment]
> What's the version that Kitana shows?

I dont fully understand how can I get kitana to show version when I cant get kitana to open.

**Comment by pannal** [comment]
Try to kill the container completely including the mounted volumes, then it should open again (not connected to a PMS), and show the version.

**Comment by k00d1** [comment]
So...  

I killed the container...
`docker kill kitana`

of course now it says failed to open page. Sorry but my understanding of docker is very limited.

**Comment by pannal** [comment]
Please do:
`docker pull pannal/kitana:latest`
`docker run --name kitana_test --restart unless-stopped -v kitana_data_test:/app/data -d -p 0.0.0.0:31337:31337 pannal/kitana:latest -B 0.0.0.0:31337`

Just to be sure you're on the latest version.
