### ISSUE TITLE
Trying to get Kitana up and running in docker with Portainer

### ISSUE THREAD

**Issue by alexander-paterson** [pannal/Kitana#42]
I've been using https://kitana.bas.sh/ for ages to use Kitana but for the last 4-5 days it's just been timing out.

So, I decided to try and try and get it up and running in Docker.

I created a Stack in Portainer and used the Docker-compose from the Kitana GitHub, my first issue was Portainer gave me an error saying Service kitana has a link service plex which is undefined.

I removed the links section and the container was created.

However, when I try to go to ip:31337 the page doesn't load.

Does anyone have any ideas on how to get Kitana running?

**Comment by MattSidney** [comment]
I seem to be having a similar issue. 
Logs look ok and no error but the page just fails to load. 

```
[02/Aug/2020:17:57:54] ENGINE Bus STARTING
[02/Aug/2020:17:57:54] ENGINE Starting SassCompilerPlugin
[02/Aug/2020:17:57:54] ENGINE Serving on http://0.0.0.0:31337
[02/Aug/2020:17:57:54] ENGINE Bus STARTED
[02/Aug/2020:17:57:54]  Starting Sass Compile
[02/Aug/2020:17:57:54]  SassCompilerPlugin: Compiling /app/static/sass to /app/static/css
[02/Aug/2020:17:57:55] ENGINE Listening for SIGTERM.
[02/Aug/2020:17:57:55] ENGINE Listening for SIGHUP.
[02/Aug/2020:17:57:55] ENGINE Listening for SIGUSR1.
```
Is there additional logs I could capture to help investigate this?

**Comment by cphmichael** [comment]
Did you upgrade to the "new Plex Movie agent"?
* https://forums.plex.tv/t/introducing-the-new-plex-movie-agent/615989

For me the problem startet after I did that.

**Comment by unabatedshagie** [comment]
Thay would stop the plugins from working on the new movie library when you try and use them, I wouldn't have thought that it would stop this external piece of software from loading.

**Comment by cphmichael** [comment]
I am using Kitana from a docker in unRAID.

Maybe you can see something from this cut from the log:

Traceback (most recent call last):
File "/usr/local/lib/python3.5/site-packages/requests/adapters.py", line 449, in send
timeout=timeout
File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 720, in urlopen
method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]

File "/usr/local/lib/python3.5/site-packages/urllib3/util/retry.py", line 436, in increment
raise MaxRetryError(_pool, url, error or ResponseError(cause))

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10-60-154-8.e04c4feead7248c882459266f35e1328.plex.direct', port=32400): Max retries exceeded with url: /video/subzero (Caused by SSLError(CertificateError("hostname '10-60-154-8.e04c4feead7248c882459266f35e1328.plex.direct' doesn't match '*.c5fd7a122bdd4c03b79ce5f1a1ad7669.plex.direct'",),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "kitana.py", line 632, in default
return self.render_plugin(path)
File "kitana.py", line 174, in render_plugin
content = self.plex_dispatch(path)
File "kitana.py", line 159, in plex_dispatch
r = self._dispatch(path)
File "kitana.py", line 154, in _dispatch
r = self.session.get(self.server_addr + path, headers=headers, params=data, **self.req_defaults)
File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 543, in get
return self.request('GET', url, **kwargs)
File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 530, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 643, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.5/site-packages/requests/adapters.py", line 514, in send
raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='10-60-154-8.e04c4feead7248c882459266f35e1328.plex.direct', port=32400): Max retries exceeded with url: /video/subzero (Caused by SSLError(CertificateError("hostname '10-60-154-8.e04c4feead7248c882459266f35e1328.plex.direct' doesn't match '*.c5fd7a122bdd4c03b79ce5f1a1ad7669.plex.direct'",),))

130.225.99.114 - - [03/Aug/2020:09:05:49] "GET /kitana HTTP/1.1" 200 - "" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/83.0.4103.61 Chrome/83.0.4103.61 Safari/537.36"
[03/Aug/2020:09:06:09] ENGINE Caught signal SIGTERM.
[03/Aug/2020:09:06:09] ENGINE Bus STOPPING
[03/Aug/2020:09:06:09] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 31337)) shut down
[03/Aug/2020:09:06:09] ENGINE Stopping SassCompilerPlugin
[03/Aug/2020:09:06:09] ENGINE Stopped thread 'Session cleanup'.
[03/Aug/2020:09:06:09] ENGINE No thread running for UpdateCheck.
[03/Aug/2020:09:06:09] ENGINE Bus STOPPED
[03/Aug/2020:09:06:09] ENGINE Bus EXITING
[03/Aug/2020:09:06:09] ENGINE Bus EXITED
[03/Aug/2020:09:06:09] ENGINE Waiting for child threads to terminate...
[03/Aug/2020:09:27:57] ENGINE Bus STARTING
[03/Aug/2020:09:27:57] ENGINE Starting SassCompilerPlugin
[03/Aug/2020:09:27:58] ENGINE Serving on http://0.0.0.0:31337
[03/Aug/2020:09:27:58] ENGINE Bus STARTED
[03/Aug/2020:09:27:58] Starting Sass Compile
[03/Aug/2020:09:27:58] SassCompilerPlugin: Compiling /app/static/sass to /app/static/css
[03/Aug/2020:09:27:58] ENGINE Listening for SIGHUP.
[03/Aug/2020:09:27:58] ENGINE Listening for SIGTERM.
[03/Aug/2020:09:27:58] ENGINE Listening for SIGUSR1.
[03/Aug/2020:10:51:13] ENGINE Started monitor thread 'Session cleanup'.
Something went wrong. Traceback (most recent call last):
File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 672, in urlopen
chunked=chunked,
File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 376, in _make_request
self._validate_conn(conn)
File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
conn.connect()
File "/usr/local/lib/python3.5/site-packages/urllib3/connection.py", line 386, in connect
_match_hostname(cert, self.assert_hostname or server_hostname)
File "/usr/local/lib/python3.5/site-packages/urllib3/connection.py", line 396, in _match_hostname
match_hostname(cert, asserted_hostname)
File "/usr/local/lib/python3.5/ssl.py", line 309, in match_hostname
% (hostname, dnsnames[0]))
ssl.CertificateError: hostname '10-60-154-8.e04c4feead7248c882459266f35e1328.plex.direct' doesn't match '*.c5fd7a122bdd4c03b79ce5f1a1ad7669.plex.direct'

**Comment by cphmichael** [comment]
I can open Kitana from Google Chrome in Incognito, so it must be an extension that gives the problem.

**Comment by cphmichael** [comment]
@unabatedshagie 
You can try "ip:31337/kitana" that works for me.

**Comment by unabatedshagie** [comment]
> @unabatedshagie
> You can try "ip:31337/kitana" that works for me.

🤦‍♂️ That worked for me, thanks!

**Comment by MattSidney** [comment]
Using the host pc ip does not work. 
I also tried the docker ip. 
I was able to get kitana up and running in a python virtual env no problem but the docker version is having the same trouble. 

Any additional logging or tests I can perform via a connection to the kitana docker instance?

**Comment by petersem** [comment]
> Thay would stop the plugins from working on the new movie library when you try and use them, I wouldn't have thought that it would stop this external piece of software from loading.

It's the /Kitana in the command. Just change it to / and recreate your container.
