### ISSUE TITLE
ModuleNotFoundError: No module named '_sass'

### ISSUE THREAD

**Issue by an3k** [pannal/Kitana#47]
```
[/share/Public/Kitana] # python3.8 kitana.py
Traceback (most recent call last):
  File "kitana.py", line 26, in <module>
    from plugins.SassCompilerPlugin import SassCompilerPlugin
  File "/share/CE_CACHEDEV1_DATA/Public/Kitana/plugins/SassCompilerPlugin.py", line 4, in <module>
    import sass
  File "/opt/lib/python3.8/site-packages/sass.py", line 26, in <module>
    import _sass
ModuleNotFoundError: No module named '_sass'
```

**Comment by an3k** [comment]
Had to remove libsass (`pip uninstall libsass`) and install it again (`pip install libsass`) which installed version 0.20.1 (previously installed was 0.19.4) and the issue was resolved.
