### ISSUE TITLE
Fails to launch in docker

### ISSUE THREAD

**Issue by BobOkisama** [pannal/Kitana#48]
Fails to pull up the webpage. this was previously working. Below is logs, ubuntu 18.0.4

      

[24/Nov/2020:19:01:12] ENGINE Bus STARTING

[24/Nov/2020:19:01:12] ENGINE Starting SassCompilerPlugin

[24/Nov/2020:19:01:12] ENGINE Serving on http://0.0.0.0:31337

[24/Nov/2020:19:01:12] ENGINE Bus STARTED

[24/Nov/2020:19:01:12]  Starting Sass Compile

[24/Nov/2020:19:01:12]  SassCompilerPlugin: Compiling /app/static/sass to /app/static/css

[24/Nov/2020:19:01:13] ENGINE Listening for SIGTERM.

[24/Nov/2020:19:01:13] ENGINE Listening for SIGUSR1.

[24/Nov/2020:19:01:13] ENGINE Listening for SIGHUP.

[24/Nov/2020:19:01:23] ENGINE Started monitor thread 'Session cleanup'.

Something went wrong. Traceback (most recent call last):

  File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 672, in urlopen

    chunked=chunked,

  File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 376, in _make_request

    self._validate_conn(conn)

  File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn

    conn.connect()

  File "/usr/local/lib/python3.5/site-packages/urllib3/connection.py", line 386, in connect

    _match_hostname(cert, self.assert_hostname or server_hostname)

  File "/usr/local/lib/python3.5/site-packages/urllib3/connection.py", line 396, in _match_hostname

    match_hostname(cert, asserted_hostname)

  File "/usr/local/lib/python3.5/ssl.py", line 309, in match_hostname

    % (hostname, dnsnames[0]))

ssl.CertificateError: hostname '192-168-0-161.6ff0b6079e1f40788613448d7a183ef6.plex.direct' doesn't match '*.e4f9bc1a42b340da887801b258cb8d32.plex.direct'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/lib/python3.5/site-packages/requests/adapters.py", line 449, in send

    timeout=timeout

  File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 720, in urlopen

    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]

  File "/usr/local/lib/python3.5/site-packages/urllib3/util/retry.py", line 436, in increment

    raise MaxRetryError(_pool, url, error or ResponseError(cause))

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='192-168-0-161.6ff0b6079e1f40788613448d7a183ef6.plex.direct', port=32400): Max retries exceeded with url: /video/subzero (Caused by SSLError(CertificateError("hostname '192-168-0-161.6ff0b6079e1f40788613448d7a183ef6.plex.direct' doesn't match '*.e4f9bc1a42b340da887801b258cb8d32.plex.direct'",),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "kitana.py", line 632, in default

    return self.render_plugin(path)

  File "kitana.py", line 174, in render_plugin

    content = self.plex_dispatch(path)

  File "kitana.py", line 159, in plex_dispatch

    r = self._dispatch(path)

  File "kitana.py", line 154, in _dispatch

    r = self.session.get(self.server_addr + path, headers=headers, params=data, **self.req_defaults)

  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 543, in get

    return self.request('GET', url, **kwargs)

  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 530, in request

    resp = self.send(prep, **send_kwargs)

  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 643, in send

    r = adapter.send(request, **kwargs)

  File "/usr/local/lib/python3.5/site-packages/requests/adapters.py", line 514, in send

    raise SSLError(e, request=request)

requests.exceptions.SSLError: HTTPSConnectionPool(host='192-168-0-161.6ff0b6079e1f40788613448d7a183ef6.plex.direct', port=32400): Max retries exceeded with url: /video/subzero (Caused by SSLError(CertificateError("hostname '192-168-0-161.6ff0b6079e1f40788613448d7a183ef6.plex.direct' doesn't match '*.e4f9bc1a42b340da887801b258cb8d32.plex.direct'",),))

192.168.0.118 - - [24/Nov/2020:19:01:23] "GET / HTTP/1.1" 200 - "" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0"

**Comment by trox88** [comment]
Same here in with synology -> docker
Delete from container and reinstall from images (v0.3.2 version) solved my problame, just need to login again. But I don't really know what was the problame, maybe a new release of plex media server. idk.

**Comment by weirdcrap** [comment]
I've also just discovered my previously working Kitana instance is now broken with a certificate mismatch like OP.

```
[16/Dec/2020:05:38:29] ENGINE Bus STARTING
[16/Dec/2020:05:38:29] ENGINE Starting SassCompilerPlugin
[16/Dec/2020:05:38:29] ENGINE Serving on http://0.0.0.0:31337
[16/Dec/2020:05:38:29] ENGINE Bus STARTED
[16/Dec/2020:05:38:29] Starting Sass Compile
[16/Dec/2020:05:38:29] SassCompilerPlugin: Compiling /app/static/sass to /app/static/css
[16/Dec/2020:05:38:30] ENGINE Listening for SIGUSR1.
[16/Dec/2020:05:38:30] ENGINE Listening for SIGTERM.
[16/Dec/2020:05:38:30] ENGINE Listening for SIGHUP.
[16/Dec/2020:05:38:33] ENGINE Started monitor thread 'Session cleanup'.
Something went wrong. Traceback (most recent call last):
File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 672, in urlopen
chunked=chunked,
File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 376, in _make_request
self._validate_conn(conn)
File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
conn.connect()
File "/usr/local/lib/python3.5/site-packages/urllib3/connection.py", line 386, in connect
_match_hostname(cert, self.assert_hostname or server_hostname)
File "/usr/local/lib/python3.5/site-packages/urllib3/connection.py", line 396, in _match_hostname
match_hostname(cert, asserted_hostname)
File "/usr/local/lib/python3.5/ssl.py", line 309, in match_hostname
% (hostname, dnsnames[0]))
ssl.CertificateError: hostname '192-168-1-254.388f496654da4c98b24ba6110f313f6b.plex.direct' doesn't match '*.dc1eef91ed0941c88512cfe90afdc635.plex.direct'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.5/site-packages/requests/adapters.py", line 449, in send
timeout=timeout
File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 720, in urlopen
method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]

File "/usr/local/lib/python3.5/site-packages/urllib3/util/retry.py", line 436, in increment
raise MaxRetryError(_pool, url, error or ResponseError(cause))

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='192-168-1-254.388f496654da4c98b24ba6110f313f6b.plex.direct', port=32400): Max retries exceeded with url: /video/trakt (Caused by SSLError(CertificateError("hostname '192-168-1-254.388f496654da4c98b24ba6110f313f6b.plex.direct' doesn't match '*.dc1eef91ed0941c88512cfe90afdc635.plex.direct'",),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "kitana.py", line 632, in default
return self.render_plugin(path)
File "kitana.py", line 174, in render_plugin
content = self.plex_dispatch(path)
File "kitana.py", line 159, in plex_dispatch
r = self._dispatch(path)
File "kitana.py", line 154, in _dispatch
r = self.session.get(self.server_addr + path, headers=headers, params=data, **self.req_defaults)
File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 543, in get
return self.request('GET', url, **kwargs)
File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 530, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 643, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.5/site-packages/requests/adapters.py", line 514, in send
raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='192-168-1-254.388f496654da4c98b24ba6110f313f6b.plex.direct', port=32400): Max retries exceeded with url: /video/trakt (Caused by SSLError(CertificateError("hostname '192-168-1-254.388f496654da4c98b24ba6110f313f6b.plex.direct' doesn't match '*.dc1eef91ed0941c88512cfe90afdc635.plex.direct'",),))
```

**Comment by trox88** [comment]
@weirdcrap For me it was enough just to repull from image.
Your option would be my second option if the first not success.

**Comment by BobOkisama** [comment]
So I also just deleted the container volume, then pulled latest. Had to set back up from scratch, which was no issue thanks to how easy they made this. Thanks guys, this worked for me. Will leave ticket open for now in case author wishes to find out WHY this has occurred, but we do have a work around.

**Comment by pannal** [comment]
Interesting. Not sure why this happens.

Rebuilding the container fixes the issue for everyone?

**Comment by weirdcrap** [comment]
Yeah clearing the config directory and pulling the latest image fixed it for me. Hasn't re-broken yet.
