### ISSUE TITLE
Kitana and IPv6 -> ERROR 500 label too long

### ISSUE THREAD

**Issue by an3k** [pannal/Kitana#60]
`500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "kitana.py", line 436, in discover_pms
    socket.create_connection((connection["address"], connection["port"]), timeout=self.timeout)
  File "/opt/lib/python3.8/socket.py", line 808, in create_connection
  File "/opt/lib/python3.8/socket.py", line 796, in create_connection
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/lib/python3.8/encodings/idna.py", line 167, in encode
UnicodeError: label too long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/opt/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/opt/lib/python3.8/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/lib/python3.8/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "kitana.py", line 510, in servers
    servers = self.discover_pms(server_name=server_name, server_addr=server_addr)
  File "kitana.py", line 439, in discover_pms
    mask_url(connection["uri"])))
  File "/share/CE_CACHEDEV1_DATA/Public/Downloads/Kitana-0.4.2/util/str_util.py", line 26, in mask_url
    return f.url
  File "/opt/lib/python3.8/site-packages/furl/furl.py", line 1540, in url
    return self.tostr()
  File "/opt/lib/python3.8/site-packages/furl/furl.py", line 1790, in tostr
    self.netloc,
  File "/opt/lib/python3.8/site-packages/furl/furl.py", line 1461, in netloc
    netloc = idna_encode(self.host)
  File "/opt/lib/python3.8/site-packages/furl/furl.py", line 92, in idna_encode
    return str(o.encode('idna').decode('utf8'))
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label too long)`

**Comment by an3k** [comment]
I can't even access http://LANIP:LANPORT/servers to chose a connection. With 0.3.2 I was able to do so and when I selected the IPv6 connection I got this error

`500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/opt/lib/python3.8/encodings/idna.py", line 167, in encode
UnicodeError: label too long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/opt/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/opt/lib/python3.8/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/lib/python3.8/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "kitana.py", line 489, in servers
    servers = self.discover_pms(server_name=server_name, server_addr=server_addr)
  File "kitana.py", line 450, in discover_pms
    print("Server set to: {}, {}".format(mask_str(server_name), mask_url(server_addr)))
  File "/share/CE_CACHEDEV1_DATA/Public/Downloads/Kitana-0.3.2/util/str_util.py", line 26, in mask_url
    return f.url
  File "/opt/lib/python3.8/site-packages/furl/furl.py", line 1540, in url
    return self.tostr()
  File "/opt/lib/python3.8/site-packages/furl/furl.py", line 1790, in tostr
    self.netloc,
  File "/opt/lib/python3.8/site-packages/furl/furl.py", line 1461, in netloc
    netloc = idna_encode(self.host)
  File "/opt/lib/python3.8/site-packages/furl/furl.py", line 92, in idna_encode
    return str(o.encode('idna').decode('utf8'))
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label too long)`

but when I chose the local LANIP connection Kitana worked without issues.
