### ISSUE TITLE
Installed on Synology DSM 7.X 

### ISSUE THREAD

**Issue by alokc83** [pannal/Kitana#77]
Docker is running. 
however when I try to access it with ip: port 
Chrome says: This site can’t be reached 
any idea what is happening here?

**Comment by pannal** [comment]
Which IP is it listening on and which IP are you trying to access?

**Comment by leberschnitzel** [comment]
I have the same problem.
```
services:
  plex:
    image: ghcr.io/linuxserver/plex
    volumes:
      - /volume1/docker/plex:/config
      - /volume1/PlexMedia/Movies:/movies
      - /volume1/PlexMedia/Shows:/shows
      - /volume1/PlexMedia/Music:/music
    network_mode: host
    environment:
      - TZ=Europe/Zurich
      - VERSION=latest
    restart: always

  kitana:
    image: pannal/kitana:latest
    container_name: kitana
    volumes:
      - /volume1/docker/kitana:/app/data
    ports:
      - 31337:31337
    links:
      - plex
    command: -B 0.0.0.0:31337 -p /kitana -P
    restart: unless-stopped
```
when trying to reach http://192.168.0.157:31337/, I get a 404.

Container log for Kitana:
```
[26/Apr/2023:07:40:00] ENGINE Bus STARTING
[26/Apr/2023:07:40:00] ENGINE Starting SassCompilerPlugin
[26/Apr/2023:07:40:00] ENGINE Serving on http://0.0.0.0:31337
[26/Apr/2023:07:40:00] ENGINE Bus STARTED
[26/Apr/2023:07:40:00]  Starting Sass Compile
[26/Apr/2023:07:40:00]  SassCompilerPlugin: Compiling /app/static/sass to /app/static/css
Traceback (most recent call last):
  File "/app/util/update.py", line 23, in update_check
    _update_check(kitana)
  File "/app/util/update.py", line 11, in _update_check
    repo = g.get_repo("pannal/Kitana")
  File "/usr/local/lib/python3.8/site-packages/github/MainClass.py", line 330, in get_repo
    headers, data = self.__requester.requestJsonAndCheck("GET", url)
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 353, in requestJsonAndCheck
    return self.__check(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.RateLimitExceededException: 403 {"message": "API rate limit exceeded for 80.218.158.63. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)", "documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
[26/Apr/2023:07:40:02] ENGINE Listening for SIGTERM.
[26/Apr/2023:07:40:02] ENGINE Listening for SIGHUP.
[26/Apr/2023:07:40:02] ENGINE Listening for SIGUSR1.
```

**Comment by leberschnitzel** [comment]
changing the command to
`command: -B 0.0.0.0:31337`
works!
thanks @ PTS

**Comment by pannal** [comment]
Yes, with `-p /kitana` you've instructed kitana to only react on /kitana URLs. You tried accessing it at / root.

**Comment by pannal** [comment]
My bad, fixed
